# Generated by Django 5.1.6 on 2025-04-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctionly', '0004_alter_product_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
