# Generated by Django 5.1.6 on 2025-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctionly', '0005_rename_bidder_bid_user_alter_product_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
