# Generated by Django 5.2 on 2025-04-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auctionly', '0007_bid_is_winning_bid_bid_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_winning_bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='razorpay_order_id',
        ),
    ]
