# Generated by Django 5.2 on 2025-04-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctionly', '0008_remove_bid_is_winning_bid_remove_bid_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
